### ISSUE TITLE
Line Highlighter Ignored on Even Lines

### ISSUE THREAD

**Issue by a11smiles** [EnlighterJS/EnlighterJS#123]
I've added a custom line highlighter color to my settings.

It works for _odd_ pages:
```css
.enlighter-t-wpcustom div.enlighter>div.enlighter-special {
    background-color: rgba(12,180,206,.3);
}
```

However, the setting is overwritten by the CSS style (which is apparently 3 lines further in the rendered CSS source):
```css
.enlighter-t-wpcustom div.enlighter>div:nth-child(even) {
    background-color: #f8f8f8;
}
```

Notice that on even lines, the highlighter has no affect.

I've therefore had to go into my WordPress theme's custom CSS configuration and add the `!important` modifier:
```css
.enlighter-t-wpcustom div.enlighter>div.enlighter-special {
    background-color: rgba(12,180,206,.3) !important;
}
```

This is obviously less than ideal, but it works for the time being.  However, the bug should be fixed.
