### ISSUE TITLE
yaml-support doesn't respect indentation / multiline-content is not closed

### ISSUE THREAD

**Issue by Iridias** [EnlighterJS/EnlighterJS#150]
The language-support for yaml will highlight multiline-content, but will not close this block when following lines have lower indentation-level.

**Example:**
```yaml
steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'hmgservices'
      repository: '$(imageName)'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildNumber)
        latest

  - task: Docker@2
    inputs:
      containerRegistry: 'hmgservices'
      repository: '$(imageName)'
      command: 'push'
      tags: |
        $(Build.BuildNumber)
        latest
```

All lines after the first `tags: |` will be considered multiline-content and highlighted as such:
![enlighterjs_wp-plugin_bug](https://user-images.githubusercontent.com/5657818/106726838-1ea90980-660b-11eb-91f6-25e4df3c1739.png)

**Expected behaviour:**
Highlighting of multiline-content should be closed after encountering lines with lower indentation-level (such as github does in the example above)

**Note:**
I used the markdown-support in the enlighterJS-wp plugin - no idea if that makes a difference. I'd doubt it, but who knows.

**Installed versions (as reported by plugin):**
Enlighter Plugin: 4.4.2 CE
EnlighterJS Version: 3.4.0
TinyMCE Extension: 5.0.1
Gutenberg Extension: 1.1.1
Theme Customizer: 2.3.0
WP-Skeleton Version: 0.28.0
